import { ImageSourcePropType } from "react-native";

export const events=[
    {
      id: 7,
      title: "~ SNOWY SPIRITS ~",
      shortDescription:"ROOFTOP @ THE BREW ESTATE",
      date: "18-12-2024",
      time: "6 PM",
      description: "🎄 CELEBRATE THE JOY OF THE SEASON WITH A MAGICAL CHRISTMAS PARTY AT THE BREW ESTATE, PATIALA! 🎅✨<br/>INDULGE IN AN EVENING FILLED WITH FESTIVE CHEER, DELICIOUS HOLIDAY TREATS, LIVE MUSIC, AND DAZZLING DECORATIONS. 🎁🎶<br/>LET’S MAKE THIS CHRISTMAS UNFORGETTABLE TOGETHER.** 🎉❄️<br/><br/> DATE: 18 DECEMBER 2024<br/> TIME: 6 PM<br/>📍 VENUE: THE BREW ESTATE, PATIALA<br/><br/>RESERVE YOUR SPOT NOW FOR A NIGHT OF MERRIMENT AND MEMORIES! 🎄✨ ",
      venue: "THE BREW ESTATE PATIALA",
      place: "https://www.google.com/maps/place/Sol+House/@30.3462194,76.3786728,15z/data=!4m2!3m1!1s0x0:0x14ccb133a32eac4d?sa=X&ved=1t:2428&ictx=111",
      photo1:require("../assets/EVENT IMAGES/SnowySpirits.png") as ImageSourcePropType,
      photo2:require("../assets/EVENT IMAGES/solhouse2.jpeg") as ImageSourcePropType,
      photo3:require("../assets/EVENT IMAGES/solhouse3.jpeg") as ImageSourcePropType,
      tags:["PARTY","XMAS 2024"]
    },
    {
      id: 6,
      title: "LAS VEGAS GRAND PRIX",
      shortDescription:"CAMPUS CONNECT x SOL HOUSE",
      date: "24-11-2024",
      time: "11 AM",
      description: "🏎️ WATCH THE F1 GRAND PRIX LAS VEGAS LIVE STREAMING ON CAMPUS CONNECT - 24TH NOVEMBER! 🏁<br/><br/>🔥 EXPERIENCE THE THRILL AS MAX VERSTAPPEN AND LANDO NORRIS BATTLE FOR THE 2024 CHAMPIONSHIP TITLE. 🏆<br/><br/> 🚥 DON'T MISS THE HIGH-SPEED ACTION, EXCLUSIVE OFFERS, AND UNFORGETTABLE RACING MOMENTS! JOIN US FOR THE ULTIMATE VIEWING EXPERIENCE. 🎉",
      venue: "SOL HOUSE PATIALA",
      place: "https://www.google.com/maps/place/Sol+House/@30.3462194,76.3786728,15z/data=!4m2!3m1!1s0x0:0x14ccb133a32eac4d?sa=X&ved=1t:2428&ictx=111",
      photo1:require("../assets/EVENT IMAGES/F1StreamParty.jpg") as ImageSourcePropType,
      photo2:require("../assets/EVENT IMAGES/solhouse2.jpeg") as ImageSourcePropType,
      photo3:require("../assets/EVENT IMAGES/solhouse3.jpeg") as ImageSourcePropType,
      tags:["LIVE STREAMING","EXCITING"]
    },
    {
      id: 5,
      title: "HALLOWEEN NIGHT PHASE 3",
      shortDescription:"CAMPUS CONNECT PRESENTS",
      date: "06-11-2024",
      time: "5 PM",
      description: "🎃 JOIN US FOR A SPOOKTACULAR HALLOWEEN NIGHT ON NOVEMBER 6TH, 2024 ! GET READY FOR A NIGHT FILLED WITH FRIGHTFUL FUN, GHOSTLY GAMES, AND HAUNTINGLY DELICIOUS TREATS! DRESS IN YOUR BEST COSTUME AND EMBRACE THE SPIRIT OF HALLOWEEN AS WE CELEBRATE WITH A MYSTERIOUS THEME. DON’T MISS OUT ON THIS FANG-TASTIC NIGHT OF THRILLS AND CHILLS! MARK YOUR CALENDARS AND BRING YOUR FRIENDS FOR AN UNFORGETTABLE EVENING! 👻",
      venue: "S LOUNGE",
      place: "https://www.google.com/maps/place/SWAGATH+RESTRO+BAR/@30.345593,76.3767147,471m/data=!3m1!1e3!4m6!3m5!1s0x391029f04e122447:0xf85d6b481f5a4562!8m2!3d30.3463626!4d76.3774221!16s%2Fg%2F11t2dzf9b3?entry=ttu",
      photo1:require("../assets/EVENT IMAGES/HalloweenNightp3.png") as ImageSourcePropType,
      photo2:require("../assets/EVENT IMAGES/SLounge4.jpg") as ImageSourcePropType,
      photo3:require("../assets/EVENT IMAGES/SLounge5.jpg") as ImageSourcePropType,
      tags:["EERIE","PARTY"]
    },
    {
      id: 4,
      title: "HALLOWEEN NIGHT PHASE 2",
      shortDescription:"CAMPUS CONNECT PRESENTS",
      date: "06-11-2024",
      time: "5 PM",
      description: "🎃 JOIN US FOR A SPOOKTACULAR HALLOWEEN NIGHT ON NOVEMBER 6TH, 2024 ! GET READY FOR A NIGHT FILLED WITH FRIGHTFUL FUN, GHOSTLY GAMES, AND HAUNTINGLY DELICIOUS TREATS! DRESS IN YOUR BEST COSTUME AND EMBRACE THE SPIRIT OF HALLOWEEN AS WE CELEBRATE WITH A MYSTERIOUS THEME. DON’T MISS OUT ON THIS FANG-TASTIC NIGHT OF THRILLS AND CHILLS! MARK YOUR CALENDARS AND BRING YOUR FRIENDS FOR AN UNFORGETTABLE EVENING! 👻",
      venue: "S LOUNGE",
      place: "https://www.google.com/maps/place/SWAGATH+RESTRO+BAR/@30.345593,76.3767147,471m/data=!3m1!1e3!4m6!3m5!1s0x391029f04e122447:0xf85d6b481f5a4562!8m2!3d30.3463626!4d76.3774221!16s%2Fg%2F11t2dzf9b3?entry=ttu",
      photo1:require("../assets/EVENT IMAGES/HalloweenNightp2.jpeg") as ImageSourcePropType,
      photo2:require("../assets/EVENT IMAGES/SLounge4.jpg") as ImageSourcePropType,
      photo3:require("../assets/EVENT IMAGES/SLounge5.jpg") as ImageSourcePropType,
      tags:["EERIE","PARTY"]
    },
    {
      id: 3,
      title: "HALLOWEEN NIGHT PHASE 1",
      shortDescription:"CAMPUS CONNECT PRESENTS",
      date: "06-11-2024",
      time: "5 PM",
      description: "🎃 JOIN US FOR A SPOOKTACULAR HALLOWEEN NIGHT ON NOVEMBER 6TH, 2024 ! GET READY FOR A NIGHT FILLED WITH FRIGHTFUL FUN, GHOSTLY GAMES, AND HAUNTINGLY DELICIOUS TREATS! DRESS IN YOUR BEST COSTUME AND EMBRACE THE SPIRIT OF HALLOWEEN AS WE CELEBRATE WITH A MYSTERIOUS THEME. DON’T MISS OUT ON THIS FANG-TASTIC NIGHT OF THRILLS AND CHILLS! MARK YOUR CALENDARS AND BRING YOUR FRIENDS FOR AN UNFORGETTABLE EVENING! 👻",
      venue: "S LOUNGE",
      place: "https://www.google.com/maps/place/SWAGATH+RESTRO+BAR/@30.345593,76.3767147,471m/data=!3m1!1e3!4m6!3m5!1s0x391029f04e122447:0xf85d6b481f5a4562!8m2!3d30.3463626!4d76.3774221!16s%2Fg%2F11t2dzf9b3?entry=ttu",
      photo1:require("../assets/EVENT IMAGES/HalloweenNightp1.jpeg") as ImageSourcePropType,
      photo2:require("../assets/EVENT IMAGES/SLounge4.jpg") as ImageSourcePropType,
      photo3:require("../assets/EVENT IMAGES/SLounge5.jpg") as ImageSourcePropType,
      tags:["EERIE","PARTY"]
    },
    {
        id: 2,
        title: "GARBA NIGHT DAY 2",
        shortDescription:"CAMPUS CONNECT x BROCODE",
        date: "10-10-2024",
        time: "5 PM",
        description: "MISSED OUT ON DAY 1? DON'T WORRY, WE'VE GOT YOU COVERED WITH DAY 2, JOIN US THIS THURSDAY AT SLOUNGE PATIALA FOR A VIBRANT GARBA NIGHT! GROOVE TO YOUR FAVOURITE MUSIC AND SIP ON REFRESHING DRINKS. GET READY FOR A NIGHT FULL OF FUN, LAUGHTER, AND UNFORGETTABLE MEMORIES.",
        venue: "S LOUNGE",
        place: "https://www.google.com/maps/place/SWAGATH+RESTRO+BAR/@30.345593,76.3767147,471m/data=!3m1!1e3!4m6!3m5!1s0x391029f04e122447:0xf85d6b481f5a4562!8m2!3d30.3463626!4d76.3774221!16s%2Fg%2F11t2dzf9b3?entry=ttu",
        photo1:require("../assets/EVENT IMAGES/GarbaNight2.png") as ImageSourcePropType,
        photo2:require("../assets/EVENT IMAGES/SLounge4.jpg") as ImageSourcePropType,
        photo3:require("../assets/EVENT IMAGES/SLounge5.jpg") as ImageSourcePropType,
        tags:["GARBA FEST","PARTY"]
      },{
        id: 1,
        title: "GARBA NIGHT",
        shortDescription:"CAMPUS CONNECT x BROCODE",
        date: "9-10-2024",
        time: "5 PM",
        description: "JOIN US THIS WEDNESDAY AT SLOUNGE PATIALA FOR A VIBRANT GARBA NIGHT! GROOVE TO YOUR FAVOURITE MUSIC AND SIP ON REFRESHING DRINKS. GET READY FOR A NIGHT FULL OF FUN, LAUGHTER, AND UNFORGETTABLE MEMORIES.",
        venue: "S LOUNGE",
        place: "https://www.google.com/maps/place/SWAGATH+RESTRO+BAR/@30.345593,76.3767147,471m/data=!3m1!1e3!4m6!3m5!1s0x391029f04e122447:0xf85d6b481f5a4562!8m2!3d30.3463626!4d76.3774221!16s%2Fg%2F11t2dzf9b3?entry=ttu",
        photo1:require("../assets/EVENT IMAGES/GarbaNight1.jpg") as ImageSourcePropType,
        photo2:require("../assets/EVENT IMAGES/SLounge4.jpg") as ImageSourcePropType,
        photo3:require("../assets/EVENT IMAGES/SLounge5.jpg") as ImageSourcePropType,
        tags:["GARBA FEST","PARTY"]
      },
  ]